DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS pedidos;

CREATE TABLE usuarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL
);

CREATE TABLE pedidos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    usuario_id INTEGER,
    producto TEXT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);